FROM python:3.12-slim
 
WORKDIR /app
 
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
 
COPY main.py .
 
# Dossier de sortie monté en volume
VOLUME ["/app/output"]
 
ENTRYPOINT ["python", "main.py"]